server:
  port: 8087
spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: dev
  http:
    multipart:
      max-file-size: 30Mb
      max-request-size: 30Mb
  devtools:
    restart:
      enabled: false
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mybatis/**/*Mapper.xml
  typeAliasesPackage: com.zhkj.nettyserver.**.domain

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  #[弃用]配置缓存和session存储方式，默认ehcache,可选redis,[弃用]调整至 spring cache goodstype【shiro.用户，权限，session，spring.cache通用】
  #[弃用]cacheType: ehcache
